CREATE TABLE appointment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    reason           VARCHAR(500)                            NOT NULL,
    patient_id       BIGINT                                  NOT NULL,
    doctor_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

CREATE TABLE department
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    head_doctor_id BIGINT                                  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE dept_doctors
(
    dept_id   BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    CONSTRAINT pk_dept_doctors PRIMARY KEY (dept_id, doctor_id)
);

CREATE TABLE doctor
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    specialisation VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);

CREATE TABLE insurance
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    policy_number VARCHAR(50)                             NOT NULL,
    provider      VARCHAR(100)                            NOT NULL,
    valid_date    date                                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_insurance PRIMARY KEY (id)
);

CREATE TABLE patient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    birth_date   date,
    email        VARCHAR(255)                            NOT NULL,
    gender       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    blood_group  VARCHAR(255)                            NOT NULL,
    insurance_id BIGINT,
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

ALTER TABLE department
    ADD CONSTRAINT uc_department_headdoctor UNIQUE (head_doctor_id);

ALTER TABLE doctor
    ADD CONSTRAINT uc_doctor_email UNIQUE (email);

ALTER TABLE insurance
    ADD CONSTRAINT uc_insurance_policynumber UNIQUE (policy_number);

ALTER TABLE patient
    ADD CONSTRAINT uc_patient_email UNIQUE (email);

ALTER TABLE patient
    ADD CONSTRAINT uc_patient_insurance UNIQUE (insurance_id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor (id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_HEADDOCTOR FOREIGN KEY (head_doctor_id) REFERENCES doctor (id);

ALTER TABLE patient
    ADD CONSTRAINT FK_PATIENT_ON_INSURANCE FOREIGN KEY (insurance_id) REFERENCES insurance (id);

ALTER TABLE dept_doctors
    ADD CONSTRAINT fk_depdoc_on_department FOREIGN KEY (dept_id) REFERENCES department (id);

ALTER TABLE dept_doctors
    ADD CONSTRAINT fk_depdoc_on_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id);